version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: lasit/csvdump
    restart: on-failure
    depends_on:
      - mongodb_container
    ports:
      - 8080:8080
    volumes:
    - ./src/main/resources/input:/usr/src/app/src/main/resources/input
volumes:
  mongodb_data_container: